DIMENSIONAL ARRAYS

In [2]:
import numpy as np

In [10]:
a = np.array([[0, 1, 2],
              [10, 11, 12]])
print(a)
print(a.shape) #returns the number of rows and columns
print(a.size) #returns the number of elements in the array (Element count)
print(a.ndim) # returns the number of dimensions the array holds in this case they're 2
print(a[1,2]) # this will return a number in row 2 and in index 2 which is 12
#this will index row 1 as 0 and column 3 as index 2 thus row 2 is index 1 thus a[1,2]
a[1,2] = -1 #here you will replace 12 with -1
print(a)

#address second row (oneth) using single index
print(a[1]) #returns the second row


[[ 0  1  2]
 [10 11 12]]
(2, 3)
6
2
12
[[ 0  1  2]
 [10 11 -1]]
[10 11 -1]
